import { Task } from "./types";

export const tasks: Task[] = [
  {
    id: "task-001",
    title: "Monthly Apparatus Check",
    category: "apparatus",
    frequency: "monthly",
    status: "pending",
    assignedApparatus: "Engine 430",
  },
  {
    id: "task-002",
    title: "Monthly Apparatus Check",
    category: "apparatus",
    frequency: "monthly",
    status: "pending",
    assignedApparatus: "Engine 432",
  },
  {
    id: "task-003",
    title: "Monthly Apparatus Check",
    category: "apparatus",
    frequency: "monthly",
    status: "pending",
    assignedApparatus: "Tanker 445",
  },
  {
    id: "task-004",
    title: "Monthly Apparatus Check",
    category: "apparatus",
    frequency: "monthly",
    status: "pending",
    assignedApparatus: "Brush 420",
  },
  {
    id: "task-005",
    title: "Monthly Apparatus Check",
    category: "apparatus",
    frequency: "monthly",
    status: "pending",
    assignedApparatus: "Brush 421",
  },
  {
    id: "task-006",
    title: "Monthly Department Training",
    category: "training",
    frequency: "monthly",
    status: "pending",
  },
  {
    id: "task-007",
    title: "Annual Apparatus Maintenance",
    category: "maintenance",
    frequency: "annually",
    status: "pending",
    assignedApparatus: "Engine 430",
  },
  {
    id: "task-008",
    title: "Annual Apparatus Maintenance",
    category: "maintenance",
    frequency: "annually",
    status: "pending",
    assignedApparatus: "Engine 432",
  },
  {
    id: "task-009",
    title: "Annual Apparatus Maintenance",
    category: "maintenance",
    frequency: "annually",
    status: "pending",
    assignedApparatus: "Tanker 445",
  },
  {
    id: "task-010",
    title: "Annual Apparatus Maintenance",
    category: "maintenance",
    frequency: "annually",
    status: "pending",
    assignedApparatus: "Brush 420",
  },
  {
    id: "task-011",
    title: "Annual Apparatus Maintenance",
    category: "maintenance",
    frequency: "annually",
    status: "pending",
    assignedApparatus: "Brush 421",
  },
  {
    id: "task-012",
    title: "Annual Ladder Inspection",
    category: "maintenance",
    frequency: "annually",
    status: "pending",
    assignedApparatus: "Engine 430",
  },
  {
    id: "task-013",
    title: "Annual Ladder Inspection",
    category: "maintenance",
    frequency: "annually",
    status: "pending",
    assignedApparatus: "Engine 432",
  },
];