import type { ReportSourceConfig } from "@/lib/reports/types";
import { MAINTENANCE_TYPE_OPTIONS } from "@/lib/maintenance";

export const REPORT_SOURCES: ReportSourceConfig[] = [
	{
		key: "deficiencies",
		name: "Deficiencies",
		description: "Status, priority, and apparatus-linked deficiency records.",
		availability: "available",
		filters: [
			{
				key: "status",
				label: "Status",
				type: "select",
				options: [
					{ value: "all", label: "All Statuses" },
					{ value: "open", label: "Open" },
					{ value: "in progress", label: "In Progress" },
					{ value: "resolved", label: "Resolved" },
					{ value: "closed", label: "Closed" },
				],
			},
			{
				key: "priority",
				label: "Priority",
				type: "select",
				options: [
					{ value: "all", label: "All Priorities" },
					{ value: "critical", label: "Critical" },
					{ value: "high", label: "High" },
					{ value: "medium", label: "Medium" },
					{ value: "low", label: "Low" },
					{ value: "informational", label: "Informational" },
				],
			},
		],
		columns: [
			{ key: "deficiency_number", label: "Deficiency #" },
			{ key: "reported_at", label: "Reported" },
			{ key: "resolved_at", label: "Resolved" },
			{ key: "status_name", label: "Status" },
			{ key: "priority_name", label: "Priority" },
			{ key: "apparatus_name", label: "Apparatus" },
			{ key: "related_item", label: "Related Item" },
			{ key: "category_name", label: "Category" },
			{ key: "reported_by", label: "Reported By" },
			{ key: "description", label: "Description" },
		],
	},
	{
		key: "training",
		name: "Training",
		description: "Course records, attendance, and training-hour summaries.",
		availability: "available",
		filters: [
			{
				key: "member_id",
				label: "Member",
				type: "select",
				options: [{ value: "all", label: "All Members" }],
			},
			{
				key: "category_id",
				label: "Training Category",
				type: "select",
				options: [{ value: "all", label: "All Categories" }],
			},
		],
		columns: [
			{ key: "training_date", label: "Date" },
			{ key: "member_name", label: "Member" },
			{ key: "training_name", label: "Training" },
			{ key: "category_name", label: "Category" },
			{ key: "hours", label: "Hours" },
			{ key: "instructor_name", label: "Instructor" },
			{ key: "training_type", label: "Type" },
			{ key: "source_type", label: "Source" },
		],
	},
	{
		key: "personnel",
		name: "Personnel",
		description: "Department roster, active status, and role information.",
		availability: "available",
		filters: [
			{
				key: "status",
				label: "Status",
				type: "select",
				options: [
					{ value: "all", label: "All Members" },
					{ value: "active", label: "Active" },
					{ value: "inactive", label: "Inactive" },
				],
			},
			{
				key: "role_id",
				label: "Role",
				type: "select",
				options: [{ value: "all", label: "All Roles" }],
			},
			{
				key: "station",
				label: "Station",
				type: "select",
				options: [{ value: "all", label: "All Stations" }],
			},
			{
				key: "shift",
				label: "Shift",
				type: "select",
				options: [{ value: "all", label: "All Shifts" }],
			},
		],
		columns: [
			{ key: "member_name", label: "Member" },
			{ key: "role_name", label: "Role" },
			{ key: "rank", label: "Rank / Position" },
			{ key: "status", label: "Status" },
			{ key: "email", label: "Email" },
			{ key: "phone", label: "Phone" },
			{ key: "station", label: "Station" },
			{ key: "shift", label: "Shift" },
			{ key: "active", label: "Active" },
		],
	},
	{
		key: "certifications",
		name: "Certifications",
		description: "Certification status and expiration evidence.",
		availability: "available",
		filters: [
			{
				key: "member_id",
				label: "Member",
				type: "select",
				options: [{ value: "all", label: "All Members" }],
			},
			{
				key: "certification_id",
				label: "Certification",
				type: "select",
				options: [{ value: "all", label: "All Certifications" }],
			},
			{
				key: "status",
				label: "Status",
				type: "select",
				options: [
					{ value: "all", label: "All Statuses" },
					{ value: "current", label: "Current" },
					{ value: "expiring", label: "Expiring" },
					{ value: "expired", label: "Expired" },
				],
			},
			{
				key: "expiration_window",
				label: "Expiration",
				type: "select",
				options: [
					{ value: "all", label: "All" },
					{ value: "next-30", label: "Next 30 Days" },
					{ value: "next-60", label: "Next 60 Days" },
					{ value: "next-90", label: "Next 90 Days" },
				],
			},
			{
				key: "date_basis",
				label: "Date Basis",
				type: "select",
				options: [
					{ value: "all-dates", label: "No Date Filter" },
					{ value: "issued-date", label: "Issued Date" },
					{ value: "expiration-date", label: "Expiration Date" },
				],
			},
		],
		columns: [
			{ key: "member_name", label: "Member" },
			{ key: "certification_name", label: "Certification" },
			{ key: "certificate_number", label: "Certificate #" },
			{ key: "issued_at", label: "Issued" },
			{ key: "expires_at", label: "Expires" },
			{ key: "status", label: "Status" },
			{ key: "days_until_expiration", label: "Days Until Expiration" },
			{ key: "supporting_document", label: "Supporting Document" },
		],
	},
	{
		key: "apparatus",
		name: "Apparatus",
		description: "Apparatus checks, status changes, and linked deficiencies.",
		availability: "available",
		filters: [
			{
				key: "report_type",
				label: "Report Type",
				type: "select",
				options: [
					{ value: "overview", label: "Overview" },
					{ value: "mileage-hours", label: "Mileage & Hours" },
				],
			},
			{
				key: "apparatus_id",
				label: "Apparatus",
				type: "select",
				options: [{ value: "all", label: "All Apparatus" }],
			},
			{
				key: "apparatus_status",
				label: "Current Status",
				type: "select",
				options: [
					{ value: "all", label: "All Statuses" },
					{ value: "ready", label: "Ready" },
					{ value: "needs_attention", label: "Needs Attention" },
					{ value: "out_of_service", label: "Out of Service" },
				],
			},
			{
				key: "check_status",
				label: "Check Status (In Period)",
				type: "select",
				options: [
					{ value: "all", label: "All Check Outcomes" },
					{ value: "ready", label: "Ready" },
					{ value: "needs_attention", label: "Needs Attention" },
					{ value: "out_of_service", label: "Out of Service" },
				],
			},
			{
				key: "inspected_by",
				label: "Checked By (In Period)",
				type: "select",
				options: [{ value: "all", label: "All Members" }],
			},
			{
				key: "check_activity",
				label: "Check Activity",
				type: "select",
				options: [
					{ value: "all", label: "All" },
					{ value: "with-checks", label: "With Checks In Period" },
					{ value: "without-checks", label: "No Checks In Period" },
				],
			},
		],
		columns: [
			{ key: "reading_date", label: "Date" },
			{ key: "entry_source", label: "Source" },
			{ key: "apparatus_name", label: "Apparatus" },
			{ key: "reading_mileage", label: "Mileage" },
			{ key: "reading_engine_hours", label: "Engine Hours" },
			{ key: "checked_by", label: "Checked By" },
			{ key: "check_status", label: "Check Status" },
			{ key: "check_notes", label: "Notes" },
			{ key: "apparatus_type", label: "Type" },
			{ key: "radio_number", label: "Radio #" },
			{ key: "apparatus_status", label: "Current Status" },
			{ key: "last_inspection_at", label: "Last Inspection" },
			{ key: "current_mileage", label: "Latest Mileage" },
			{ key: "current_engine_hours", label: "Latest Engine Hours" },
			{ key: "checks_in_period", label: "Checks In Period" },
			{ key: "ready_checks", label: "Ready Checks" },
			{ key: "needs_attention_checks", label: "Needs Attention Checks" },
			{ key: "out_of_service_checks", label: "Out of Service Checks" },
			{ key: "latest_check_at", label: "Latest Check In Period" },
			{ key: "latest_check_by", label: "Latest Checked By" },
			{ key: "latest_check_status", label: "Latest Check Status" },
			{ key: "latest_check_mileage", label: "Latest Check Mileage" },
			{ key: "latest_check_engine_hours", label: "Latest Check Engine Hours" },
			{ key: "deficiencies_in_period", label: "Deficiencies In Period" },
			{ key: "open_deficiencies", label: "Open Deficiencies" },
			{ key: "latest_deficiency_number", label: "Latest Deficiency #" },
			{ key: "latest_deficiency_status", label: "Latest Deficiency Status" },
			{ key: "latest_deficiency_priority", label: "Latest Deficiency Priority" },
			{ key: "latest_deficiency_reported", label: "Latest Deficiency Reported" },
			{ key: "latest_deficiency_resolved", label: "Latest Deficiency Resolved" },
			{ key: "latest_deficiency_description", label: "Latest Deficiency Description" },
			{ key: "maintenance_in_period", label: "Maintenance In Period" },
			{ key: "latest_maintenance_date", label: "Latest Maintenance Date" },
			{ key: "latest_maintenance_number", label: "Latest Maintenance #" },
			{ key: "latest_maintenance_type", label: "Latest Maintenance Type" },
			{ key: "latest_maintenance_performed_by", label: "Latest Maintenance By" },
			{ key: "latest_maintenance_mileage", label: "Latest Maintenance Mileage" },
			{ key: "latest_maintenance_engine_hours", label: "Latest Maintenance Engine Hours" },
			{ key: "latest_maintenance_labor_hours", label: "Latest Maintenance Labor Hours" },
			{ key: "latest_maintenance_cost", label: "Latest Maintenance Cost" },
			{ key: "latest_maintenance_deficiency", label: "Latest Maintenance Deficiency" },
		],
	},
	{
		key: "inventory",
		name: "Inventory",
		description: "Inventory item status, location, assignment, and inspection evidence.",
		availability: "available",
		filters: [
			{
				key: "inventory_category",
				label: "Inventory Type",
				type: "select",
				options: [
					{ value: "all", label: "All Inventory" },
					{ value: "fire-hose", label: "Fire Hose" },
					{ value: "scba-cylinders", label: "SCBA Cylinders" },
					{ value: "scba-packs", label: "SCBA Packs" },
					{ value: "portable-radios", label: "Portable Radios" },
					{ value: "portable-radio-mics", label: "Portable Radio Mics" },
					{ value: "fire-extinguishers", label: "Fire Extinguishers" },
					{ value: "thermal-cameras", label: "Thermal Imaging Cameras" },
					{ value: "gas-monitors", label: "Gas Monitors" },
					{ value: "rope", label: "Rope" },
					{ value: "misc-fire-equipment", label: "Misc Fire Equipment" },
					{ value: "ems-equipment", label: "EMS Equipment" },
					{ value: "batteries", label: "Batteries" },
					{ value: "ground-ladders", label: "Ground Ladders" },
					{ value: "pie", label: "PIE Equipment" },
					{ value: "ppe", label: "PPE" },
					{ value: "ems-supplies", label: "EMS Supplies" },
				],
			},
			{
				key: "inventory_report_type",
				label: "Report Type",
				type: "select",
				options: [{ value: "inventory", label: "Inventory" }],
			},
		],
		columns: [
			{ key: "inventory_type", label: "Inventory Type" },
			{ key: "item_name", label: "Item" },
			{ key: "identifier", label: "Identifier" },
			{ key: "serial_number", label: "Serial #" },
			{ key: "status", label: "Status" },
			{ key: "location_or_apparatus", label: "Location / Apparatus" },
			{ key: "latest_activity", label: "Latest Activity" },
			{ key: "latest_result", label: "Latest Result" },
			{ key: "due_date", label: "Due Date" },
			{ key: "open_deficiencies", label: "Open Deficiencies", align: "right" },
		],
	},
	{
		key: "maintenance",
		name: "Maintenance",
		description: "Maintenance schedules, completion records, and notes.",
		availability: "available",
		filters: [
			{
				key: "apparatus_id",
				label: "Apparatus",
				type: "select",
				options: [{ value: "all", label: "All Apparatus" }],
			},
			{
				key: "maintenance_type",
				label: "Maintenance Type",
				type: "select",
				options: [
					{ value: "all", label: "All Types" },
					...MAINTENANCE_TYPE_OPTIONS.map((option) => ({ value: option.toLowerCase(), label: option })),
				],
			},
			{
				key: "completed_by",
				label: "Performed By",
				type: "select",
				options: [{ value: "all", label: "All Members" }],
			},
			{
				key: "linked_deficiency",
				label: "Deficiency Link",
				type: "select",
				options: [
					{ value: "all", label: "All" },
					{ value: "linked", label: "Linked" },
					{ value: "unlinked", label: "Unlinked" },
				],
			},
		],
		columns: [
			{ key: "service_date", label: "Date" },
			{ key: "maintenance_number", label: "Record #" },
			{ key: "apparatus_name", label: "Apparatus" },
			{ key: "maintenance_type", label: "Maintenance Type" },
			{ key: "description", label: "Description / Work Performed" },
			{ key: "performed_by", label: "Performed By" },
			{ key: "mileage", label: "Mileage" },
			{ key: "engine_hours", label: "Engine Hours" },
			{ key: "labor_hours", label: "Labor Hours" },
			{ key: "cost", label: "Cost" },
			{ key: "related_deficiency", label: "Related Deficiency" },
			{ key: "parts_used", label: "Parts Used" },
			{ key: "notes", label: "Notes" },
			{ key: "photo_count", label: "Photos" },
			{ key: "attachment_count", label: "Attachments" },
		],
	},
	{
		key: "pre-plans",
		name: "Pre-Plans",
		description: "Pre-plan records and site details.",
		availability: "available",
		filters: [],
		columns: [
			{ key: "business_name", label: "Business" },
			{ key: "address", label: "Address" },
			{ key: "city", label: "City" },
			{ key: "state", label: "State" },
			{ key: "zip", label: "ZIP" },
			{ key: "occupancy_id_number", label: "Occupancy ID" },
			{ key: "last_verified_at", label: "Last Verified" },
			{ key: "updated_at", label: "Updated" },
			{ key: "primary_contact_name", label: "Primary Contact" },
			{ key: "primary_contact_phone", label: "Contact Phone" },
			{ key: "normal_occupant_load", label: "Occupant Load" },
			{ key: "hydrant_count", label: "Hydrants" },
			{ key: "hazard_count", label: "Hazards" },
			{ key: "critical_information", label: "Critical Information" },
		],
	},
	{
		key: "ems",
		name: "EMS",
		description: "EMS equipment, certifications, and training records across the department.",
		availability: "available",
		filters: [
			{
				key: "report_type",
				label: "Report Type",
				type: "select",
				options: [
					{ value: "certification-status", label: "EMS Certification Status" },
					{ value: "training", label: "EMS Training" },
					{ value: "equipment", label: "EMS Equipment" },
					{ value: "supplies", label: "EMS Supplies" },
				],
			},
			{
				key: "report_scope",
				label: "Report Scope",
				type: "select",
				options: [
					{ value: "iowa", label: "Iowa" },
					{ value: "nremt", label: "NREMT" },
					{ value: "iowa-and-nremt", label: "Iowa + NREMT" },
				],
			},
			{
				key: "member_id",
				label: "Member",
				type: "select",
				options: [{ value: "all", label: "All Members" }],
			},
			{
				key: "training_category_id",
				label: "EMS Training Category",
				type: "select",
				options: [{ value: "all", label: "All EMS Training" }],
			},
			{
				key: "equipment_id",
				label: "Equipment",
				type: "select",
				options: [{ value: "all", label: "All Equipment" }],
			},
			{
				key: "equipment_status",
				label: "Equipment Status",
				type: "select",
				options: [
					{ value: "all", label: "All Equipment Statuses" },
					{ value: "active", label: "Active" },
					{ value: "inactive", label: "Inactive" },
				],
			},
			{
				key: "supply_id",
				label: "Supply Item",
				type: "select",
				options: [{ value: "all", label: "All Supplies" }],
			},
			{
				key: "supply_status",
				label: "Supply Status",
				type: "select",
				options: [
					{ value: "all", label: "All Supply Statuses" },
					{ value: "active", label: "Active" },
					{ value: "inactive", label: "Inactive" },
				],
			},
			{
				key: "supply_stock_level",
				label: "Stock Level",
				type: "select",
				options: [
					{ value: "all", label: "All Stock Levels" },
					{ value: "normal", label: "Normal" },
					{ value: "low", label: "Low" },
					{ value: "critical", label: "Critical" },
					{ value: "out_of_stock", label: "Out of Stock" },
					{ value: "low_or_worse", label: "Low, Critical, or Out of Stock" },
				],
			},
			{
				key: "certification_status",
				label: "Certification Status",
				type: "select",
				options: [
					{ value: "all", label: "All Certification Statuses" },
					{ value: "current", label: "Current" },
					{ value: "expiring", label: "Expiring" },
					{ value: "expired", label: "Expired" },
				],
			},
			{
				key: "ems_level",
				label: "EMS Certification Level",
				type: "select",
				options: [
					{ value: "all", label: "All Levels" },
					{ value: "emr", label: "EMR" },
					{ value: "emt", label: "EMT" },
					{ value: "aemt", label: "AEMT" },
					{ value: "paramedic", label: "Paramedic" },
				],
			},
			{
				key: "iowa_status",
				label: "Iowa EMS Status",
				type: "select",
				options: [
					{ value: "all", label: "All Iowa Statuses" },
					{ value: "active", label: "Active" },
					{ value: "inactive", label: "Inactive" },
					{ value: "expired", label: "Expired" },
					{ value: "needs_review", label: "Needs Review" },
				],
			},
			{
				key: "nremt_maintained",
				label: "NREMT Maintained",
				type: "select",
				options: [
					{ value: "all", label: "All" },
					{ value: "yes", label: "Yes" },
					{ value: "no", label: "No" },
				],
			},
			{
				key: "readiness_status",
				label: "Readiness Status",
				type: "select",
				options: [
					{ value: "all", label: "All Statuses" },
					{ value: "complete", label: "Complete" },
					{ value: "on_track", label: "On Track" },
					{ value: "needs_attention", label: "Needs Attention" },
					{ value: "not_maintained", label: "Not Maintained" },
					{ value: "no_track", label: "No EMS Track Configured" },
				],
			},
			{
				key: "expiration_window",
				label: "Expiration",
				type: "select",
				options: [
					{ value: "all", label: "All" },
					{ value: "expired", label: "Expired" },
					{ value: "next-30", label: "Next 30 Days" },
					{ value: "next-60", label: "Next 60 Days" },
					{ value: "next-90", label: "Next 90 Days" },
					{ value: "no-expiration", label: "No Expiration" },
				],
			},
		],
		columns: [
			{ key: "record_type", label: "Record Type" },
			{ key: "member_name", label: "Member" },
			{ key: "item_name", label: "Item / Course" },
			{ key: "category_name", label: "Category" },
			{ key: "status", label: "Status" },
			{ key: "date", label: "Date" },
			{ key: "location", label: "Location" },
			{ key: "hours", label: "Hours" },
			{ key: "expires_at", label: "Expires" },
		],
	},
	{
		key: "inspections",
		name: "Inspections",
		description: "Centralized inspection and testing records across inventory systems.",
		availability: "available",
		filters: [
			{
				key: "report_type",
				label: "Report Type",
				type: "select",
				options: [
					{ value: "all-inspections", label: "All Inspections" },
					{ value: "fire-hose-testing", label: "Fire Hose Testing" },
					{ value: "scba-cylinder-hydrostatic-testing", label: "SCBA Cylinder Hydrostatic Testing" },
					{ value: "scba-pack-flow-testing", label: "SCBA Pack Flow Testing" },
					{ value: "gas-monitor-calibration", label: "Gas Monitor Calibration" },
					{ value: "rope-inspections", label: "Rope Inspections" },
					{ value: "ground-ladder-service-testing", label: "Ground Ladder Service Testing" },
				],
			},
			{
				key: "fire_hose_id",
				label: "Fire Hose",
				type: "select",
				options: [{ value: "all", label: "All Fire Hose" }],
			},
			{
				key: "scba_cylinder_id",
				label: "SCBA Cylinder",
				type: "select",
				options: [{ value: "all", label: "All SCBA Cylinders" }],
			},
			{
				key: "scba_pack_id",
				label: "SCBA Pack",
				type: "select",
				options: [{ value: "all", label: "All SCBA Packs" }],
			},
			{
				key: "gas_monitor_id",
				label: "Gas Monitor",
				type: "select",
				options: [{ value: "all", label: "All Gas Monitors" }],
			},
			{
				key: "rope_item_id",
				label: "Rope",
				type: "select",
				options: [{ value: "all", label: "All Rope Items" }],
			},
			{
				key: "ground_ladder_id",
				label: "Ground Ladder",
				type: "select",
				options: [{ value: "all", label: "All Ground Ladders" }],
			},
			{
				key: "inspection_result",
				label: "Result",
				type: "select",
				options: [
					{ value: "all", label: "All" },
					{ value: "pass", label: "Pass" },
					{ value: "fail", label: "Fail" },
					{ value: "passed", label: "Passed" },
					{ value: "failed", label: "Failed" },
				],
			},
			{
				key: "due_status",
				label: "Due Status",
				type: "select",
				options: [
					{ value: "all", label: "All" },
					{ value: "overdue", label: "Overdue" },
					{ value: "due_soon", label: "Due Soon" },
					{ value: "current", label: "Current" },
					{ value: "no_due_date", label: "No Due Date" },
				],
			},
		],
		columns: [
			{ key: "inspection_date", label: "Date" },
			{ key: "inspection_type", label: "Inspection Type" },
			{ key: "item_name", label: "Item" },
			{ key: "item_identifier", label: "Identifier" },
			{ key: "result", label: "Result" },
			{ key: "inspected_by", label: "Inspector / Tester" },
			{ key: "item_status", label: "Item Status" },
			{ key: "next_due_date", label: "Next Due" },
			{ key: "due_status", label: "Due Status" },
			{ key: "open_deficiencies", label: "Open Deficiencies", align: "right" },
			{ key: "notes", label: "Notes" },
		],
	},
	{
		key: "activity",
		name: "Activity",
		description: "Centralized timeline of real operational events recorded across modules.",
		availability: "available",
		filters: [
			{
				key: "member_id",
				label: "Member",
				type: "select",
				options: [{ value: "all", label: "All Members" }],
			},
			{
				key: "module",
				label: "Module",
				type: "select",
				options: [
					{ value: "all", label: "All Modules" },
					{ value: "apparatus checks", label: "Apparatus Checks" },
					{ value: "calendar", label: "Calendar" },
					{ value: "certifications", label: "Certifications" },
					{ value: "deficiencies", label: "Deficiencies" },
					{ value: "maintenance", label: "Maintenance" },
					{ value: "pre-plans", label: "Pre-Plans" },
					{ value: "training", label: "Training" },
				],
			},
			{
				key: "action",
				label: "Action",
				type: "select",
				options: [
					{ value: "all", label: "All Actions" },
					{ value: "created", label: "Created" },
					{ value: "scheduled", label: "Scheduled" },
					{ value: "updated", label: "Updated" },
					{ value: "reported", label: "Reported" },
					{ value: "resolved", label: "Resolved" },
					{ value: "completed", label: "Completed" },
					{ value: "submitted", label: "Submitted" },
					{ value: "reviewed", label: "Reviewed" },
				],
			},
		],
		columns: [
			{ key: "activity_date", label: "Date / Time" },
			{ key: "member_name", label: "Member" },
			{ key: "module", label: "Module" },
			{ key: "action", label: "Action" },
			{ key: "description", label: "Description" },
			{ key: "related_item", label: "Related Item" },
		],
	},
];

export function getReportSourceConfig(categoryKey: string) {
	return REPORT_SOURCES.find((item) => item.key === categoryKey) ?? null;
}
